#define PORT 4442
#define IP_ADDR "172.19.127.63"
//#define IP_ADDR "127.0.0.1"
int getRival(int game, int actual);
char* checkAnswer(int id_game, int response2, int response, char* username);
void getNewQuestions(int id_game, char socket_com[1024], int newSocket, char response[4], char* answers, int id_player2);
int checkUsernamePassword(char *username, char *password);
int insertPlayerIntoDB(char *username, char *password);
void beginGame(char *username);
void addIterationGame(int id_game);
int getIteration(int id_game);
char* getTwoPreQuestionsLastPLayer(int game);
void setSelectedAnswer(int optionSelected, int id_game, int id_question);
char* getTwoQuestionsLastPLayer(int game);
char* getAllGamesAndStatisticsForPlayer(int player);
char* getRightAndWrongPlayer(int player);
int getCorrectAnswer(int game, int question);
char* getPlayersToGame(char *username);
char* getPlayersToGame2(char *username);
char* getGamesInProcess(char* username);
char* getPointsGame(int id_game);
void deleteQuestion(int id_q);
void updateValueQuestion(int id_q, int value);
void insertNewQuestion(char* question, char* op1, char* op2, char* op3, int value);
char* getAllQuestionsInfo();
static int callback(void *NotUsed, int argc, char **argv, char **azColName);
void updateGoodAnswerStatistics(int player, int game);
void updateBadAnswerStatistics(int player, int game);
void changeTurnGame(int id_game, int playerTurn);
int createStatistics(int player, int game);
int makeGame(char *player2, char *username);
int getNewIdGame();
int getActualIdGame(char *username);
int getQuestionId();
void insertPlayer(int id_game, int id_player1, int id_player2);
int insertQuestionToGame(int id_game, int id_question);
char* getQuestionData(int id_question);
void addMiss(int id_question);
void addSuccess(int id_question);
void addPoints(int id_game, int id_player, int points);
void updateLevel(int points, int player, int game);
int getValueQuestion(int id_question);
int getGoodOption(int id_game, int id_question);
void setCorrectAnswer(int optionSelected, int id_game, int id_question);
int getTurnPlayer(int id_game);
void printClientTitle();
void printServerTitle();
sqlite3* openDatabase();
void closeDatabase(sqlite3* db);
sqlite3_stmt *stmt;